version: "3.9"

services:
  db:
    container_name: spring_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
      POSTGRES_DB: springboot_course

    volumes:
      - db:/data/postgres
    restart: no

volumes:
  db:
