version: "3.9"

services:
  db:
    container_name: spring_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
      POSTGRES_DB: springboot_course

    volumes:
      - db:/data/postgres

#    networks:
#      - postgres

    restart: no

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"

#    networks:
#      - postgres

    restart: no

#networks:
#  postgres:
#    driver: bridge

volumes:
  db:
  pgadmin:
